// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbY2ePtGpyh53f04XLCKR4IM_Uyw_7His',
    appId: '1:679551213464:web:c5ecc33fc6d16f076855ed',
    messagingSenderId: '679551213464',
    projectId: 'projectx-18f25',
    authDomain: 'projectx-18f25.firebaseapp.com',
    storageBucket: 'projectx-18f25.firebasestorage.app',
    measurementId: 'G-G7XQ561F3S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm3XenBGphXDYwK0lr_X0Yc1ZRTMr4U1A',
    appId: '1:679551213464:android:13353e312d97f5496855ed',
    messagingSenderId: '679551213464',
    projectId: 'projectx-18f25',
    storageBucket: 'projectx-18f25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT3mFnSYbo0sm_ceIR1kqFNSorXJhOiys',
    appId: '1:679551213464:ios:96f45b2659c845356855ed',
    messagingSenderId: '679551213464',
    projectId: 'projectx-18f25',
    storageBucket: 'projectx-18f25.firebasestorage.app',
    iosBundleId: 'com.example.chattr',
  );

}